import { useEffect, useMemo, useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { api, getToken, setToken, clearToken } from './lib/api.js';

const EMPTY = { employeeName:'', rollNumber:'', designation:'', department:'', companyName:'VigVen Tech Mark Private Limited', email:'', phone:'+91-80-2333-9220', linkedin:'', website:'https://www.vigven.com', address:'#26, 2nd Floor, 2nd Main Road, RBI Colony, Ananda Nagar, Bengaluru, Karnataka, 560024', employeeImage:'', active:true };

function initials(name=''){ return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join(''); }
function basePath(){ return import.meta.env.BASE_URL || '/'; }
function cardUrl(id){ return `${window.location.origin}${window.location.pathname}#/card/${id}`; }
function resizeImage(file){ return new Promise((resolve,reject)=>{ if(!file?.type.startsWith('image/')) return reject(new Error('Please select an image file.')); const r=new FileReader(); r.onerror=()=>reject(new Error('Could not read the image.')); r.onload=()=>{ const img=new Image(); img.onerror=()=>reject(new Error('Could not process the image.')); img.onload=()=>{ const max=400, scale=Math.min(1,max/Math.max(img.width,img.height)); const c=document.createElement('canvas'); c.width=Math.max(1,Math.round(img.width*scale)); c.height=Math.max(1,Math.round(img.height*scale)); c.getContext('2d').drawImage(img,0,0,c.width,c.height); resolve(c.toDataURL('image/jpeg',0.78)); }; img.src=r.result; }; r.readAsDataURL(file); }); }
function downloadVCard(e){ const text=['BEGIN:VCARD','VERSION:3.0',`N:${e.employeeName};;;;`,`FN:${e.employeeName}`,e.designation?`TITLE:${e.designation}`:'',e.companyName?`ORG:${e.companyName}`:'',e.email?`EMAIL:${e.email}`:'',e.phone?`TEL:${e.phone}`:'',e.website?`URL:${e.website}`:'',e.address?`ADR:;;${e.address};;;;`:'','END:VCARD'].filter(Boolean).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type:'text/vcard'})); a.download=`${e.employeeName.replace(/\s+/g,'_')}.vcf`; a.click(); }

function Login({onLogin}){ const [p,setP]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false); async function submit(e){e.preventDefault();setBusy(true);setErr('');try{await api.login(p);setToken(p);onLogin();}catch(x){setErr(x.message)}finally{setBusy(false)}} return <main className="login"><form onSubmit={submit} className="login-card"><div className="mark">DBC</div><h1>Admin sign in</h1><p>Manage the employee digital card directory.</p><input autoFocus type="password" placeholder="Admin password" value={p} onChange={e=>setP(e.target.value)}/>{err&&<div className="error">{err}</div>}<button disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form></main>; }

function EmployeeModal({initial,onClose,onSaved}){ const [v,setV]=useState({...EMPTY,...(initial||{})}),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[imgBusy,setImgBusy]=useState(false); const edit=!!initial; const set=(k,x)=>setV(s=>({...s,[k]:x})); async function photo(e){const f=e.target.files?.[0];if(!f)return;setImgBusy(true);setErr('');try{set('employeeImage',await resizeImage(f))}catch(x){setErr(x.message)}finally{setImgBusy(false);e.target.value=''}} async function save(e){e.preventDefault();if(!v.employeeName.trim()||!v.rollNumber.trim()){setErr('Employee name and roll number are required.');return}setBusy(true);try{if(edit)await api.update(initial.id,v);else await api.create(v);onSaved()}catch(x){setErr(x.message)}finally{setBusy(false)}} return <div className="overlay"><form className="modal" onSubmit={save}><h2>{edit?'Edit employee':'Add employee'}</h2><div className="grid">{[['employeeName','Employee name',true],['rollNumber','Employee / roll number',true],['designation','Designation'],['department','Department'],['companyName','Company name'],['email','Email'],['phone','Phone'],['linkedin','LinkedIn URL'],['website','Website'],['address','Address']].map(([k,l,req])=><label key={k}>{l}{req?' *':''}<input value={v[k]||''} onChange={e=>set(k,e.target.value)} /></label>)}<label className="wide">Employee photo<input type="file" accept="image/*" onChange={photo}/><small>Optional. Resized automatically.</small>{v.employeeImage&&<div className="photo-preview"><img src={v.employeeImage} alt="preview"/><button type="button" className="secondary" onClick={()=>set('employeeImage','')}>Remove photo</button></div>}</label></div>{err&&<div className="error">{err}</div>}<div className="actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button disabled={busy||imgBusy}>{imgBusy?'Processing photo…':busy?'Saving…':edit?'Save changes':'Add employee'}</button></div></form></div>; }

function QrModal({employee,onClose}){const url=cardUrl(employee.id);return <div className="overlay"><div className="modal small"><h2>{employee.employeeName}'s QR</h2><p className="url">{url}</p><div className="qrbox"><QRCodeSVG value={url} size={210} includeMargin /></div><div className="actions"><button className="secondary" onClick={onClose}>Close</button><button onClick={()=>{const svg=document.querySelector('.qrbox svg');const data=new XMLSerializer().serializeToString(svg);const img=new Image();const u=URL.createObjectURL(new Blob([data],{type:'image/svg+xml'}));img.onload=()=>{const c=document.createElement('canvas');c.width=1600;c.height=1600;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,1600,1600);x.drawImage(img,0,0,1600,1600);c.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`${employee.employeeName.replace(/\s+/g,'_')}_QR.png`;a.click();},'image/png');URL.revokeObjectURL(u)};img.src=u;}}>Download PNG</button></div></div></div>}

function Admin(){const [authed,setAuthed]=useState(!!getToken()),[employees,setEmployees]=useState([]),[q,setQ]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[target,setTarget]=useState(null),[qr,setQr]=useState(null),[del,setDel]=useState(null); async function load(){setBusy(true);setErr('');try{setEmployees((await api.list()).employees||[])}catch(x){if(x.message.includes('Not authorized')){clearToken();setAuthed(false)}else setErr(x.message)}finally{setBusy(false)}} useEffect(()=>{if(authed)load()},[authed]); const filtered=useMemo(()=>{const s=q.trim().toLowerCase();return s?employees.filter(e=>[e.employeeName,e.rollNumber,e.designation,e.department,e.email,e.phone].join(' ').toLowerCase().includes(s)):employees},[employees,q]); if(!authed)return <Login onLogin={()=>setAuthed(true)}/>; return <main className="admin"><header><div><div className="eyebrow">VIGVEN</div><h1>Employee directory</h1></div><button className="secondary" onClick={()=>{clearToken();setAuthed(false)}}>Log out</button></header><section className="toolbar"><input placeholder="Search name, ID, designation…" value={q} onChange={e=>setQ(e.target.value)}/><button onClick={()=>setTarget('new')}>+ Add employee</button></section>{err&&<div className="error">{err}</div>}<div className="table"><table><thead><tr><th>Name</th><th>Roll No.</th><th>Designation</th><th>Department</th><th>Email</th><th>Phone</th><th>QR</th><th></th></tr></thead><tbody>{busy?<tr><td colSpan="8">Loading…</td></tr>:filtered.length===0?<tr><td colSpan="8">No employees yet.</td></tr>:filtered.map(e=><tr key={e.id}><td><b>{e.employeeName}</b></td><td>{e.rollNumber}</td><td>{e.designation}</td><td>{e.department}</td><td>{e.email}</td><td>{e.phone}</td><td><button className="tiny" onClick={()=>setQr(e)}>View QR</button></td><td><button className="tiny" onClick={()=>setTarget(e)}>Edit</button> <button className="tiny danger" onClick={()=>setDel(e)}>Delete</button></td></tr>)}</tbody></table></div>{target&&<EmployeeModal initial={target==='new'?null:target} onClose={()=>setTarget(null)} onSaved={()=>{setTarget(null);load()}}/>}{qr&&<QrModal employee={qr} onClose={()=>setQr(null)}/>} {del&&<div className="overlay"><div className="modal small"><h2>Delete employee?</h2><p>This removes {del.employeeName} and their QR link will stop working.</p><div className="actions"><button className="secondary" onClick={()=>setDel(null)}>Cancel</button><button onClick={async()=>{try{await api.remove(del.id);setDel(null);load()}catch(x){setErr(x.message)}}}>Delete</button></div></div></div>}</main>}

function Card({id}){const [e,setE]=useState(null),[err,setErr]=useState('');useEffect(()=>{api.card(id).then(x=>setE(x.employee)).catch(x=>setErr(x.message))},[id]);if(err)return <main className="card-page"><div className="card-panel center">This card couldn't be found.</div></main>;if(!e)return <main className="card-page"><div className="card-panel center">Loading card…</div></main>;return <main className="card-page"><div className="card-panel"><div className="brand">VIGVEN</div>{e.employeeImage?<img className="avatar photo" src={e.employeeImage} alt={e.employeeName}/>:<div className="avatar">{initials(e.employeeName)}</div>}<h1>{e.employeeName}</h1><div className="title">{e.designation}</div>{e.department&&<div className="dept">{e.department}</div>}<div className="divider"/><div className="details">{e.email&&<div><span>Email</span><a href={`mailto:${e.email}`}>{e.email}</a></div>}{e.phone&&<div><span>Phone</span><a href={`tel:${e.phone}`}>{e.phone}</a></div>}{e.website&&<div><span>Website</span><a href={e.website} target="_blank" rel="noreferrer">{e.website.replace(/^https?:\/\//,'')}</a></div>}{e.linkedin&&<div><span>LinkedIn</span><a href={e.linkedin} target="_blank" rel="noreferrer">View profile</a></div>}{e.address&&<div><span>Address</span><p>{e.address}</p></div>}</div><button className="save" onClick={()=>downloadVCard(e)}>Save to contacts</button><div className="shareqr"><QRCodeSVG value={window.location.href} size={82}/><small>Scan to share this card</small></div></div></main>}

export default function App(){const [hash,setHash]=useState(window.location.hash);useEffect(()=>{const h=()=>setHash(window.location.hash);window.addEventListener('hashchange',h);return()=>window.removeEventListener('hashchange',h)},[]);const m=hash.match(/^#\/card\/([^/]+)$/);return m?<Card id={decodeURIComponent(m[1])}/>:<Admin/>;}
